### ISSUE TITLE
Adjust controls (strafe + mouse view etc) for FPV

### ISSUE THREAD

**Issue by philhzss** [fordcars/OttoMatic-VR#1]
In VR moving the player's viewpoint by turning will be a big nono. Must adapt the controls to make player strafe and not turn when using the A and D keys (or left arrow right arrow)

Will work on this as part of the first person camera mode

**Comment by foote-darrell** [comment]
Is there any pre-compiled executable build of this for Windows? Or do I have to compile it myself? I have an HTC Vive and Valve Index, but don't know how to compile it for Windows.

The links to the builds seem to be of the original fork. I am new to this, and having a hard time figuring out to compile a Windows version. Where can I get a build of this VR port on Windows?

**Comment by philhzss** [comment]
> Is there any pre-compiled executable build of this for Windows? Or do I have to compile it myself? I have an HTC Vive and Valve Index, but don't know how to compile it for Windows.
> 
> The links to the builds seem to be of the original fork. I am new to this, and having a hard time figuring out to compile a Windows version. Where can I get a build of this VR port on Windows?

Hey there,
Thanks for your interest but we just started working on this about 5 days ago! The game won't be playable in VR for at least a month, probably several months until it's good enough to be played. We are just starting to port it, so far we haven't done much 

I'll let you know when it's done though

**Comment by foote-darrell** [comment]
Are there ways to beta-test it?

**Comment by philhzss** [comment]
> Are there ways to beta-test it?

Sure feel free to download the repo and just run it, every little update we do is public!! However for now you cannot play this in VR yet, even we can't. My bro is working on getting the VR rendering to work, and I'm currently working on the input system. If you really want to try it, you can download the vrcontrols branch and you (should) be able to use your VR controllers to play the game (in non VR, the game does not run in VR yet). It is very buggy and work in progress though!

It'll take a while before it works, and when it does we will make a release and I'll let you know! In the mean time of course you can download everything and run it but it probably won't be very fun :/

**Comment by foote-darrell** [comment]
How do I compile it to test it out? I followed the instructions from the Build markdown file to build it in Windows, but it reports errors. How do I run it?

**Comment by philhzss** [comment]
Im not really sure if the instructions are up to date sadly. Did you download the openvr.dll too? And did Cmake give any errors?

**Comment by foote-darrell** [comment]
I think I cloned the whole repository. It ought to have had everything in it. I will check.

**Comment by philhzss** [comment]
Hmmm alright. I suppose you saw it in the build.md file but I think you also have to separately download the SDL stuff. Were you able to build the visual studio solution, is the error you're getting in Cmake or when building the project in MSVC?

**Comment by foote-darrell** [comment]
Is openvr.dll in this repository? I can't seem to find it in the files here. Where do I find the SDL stuff in reference?

**Comment by foote-darrell** [comment]
I did try the instructions in the build markdown file with this repositry. I am using Windows. It still says there is a error. [Here is how it went down.](https://pastebin.com/xqfMffqr)

How are you compiling it to test it out?

**Comment by fordcars** [comment]
Hi Darell,

It appears CMake cannot find SDL. Did you download [SDL2-devel-2.0.16-VC.zip](http://libsdl.org/release/SDL2-devel-2.0.16-VC.zip) and extract the contents into the extern folder?

You will also need to download [OpenVR SDK 1.16.8 ](https://github.com/ValveSoftware/openvr/archive/refs/tags/v1.16.8.zip) and extract its contents into the extern folder if you haven't already.

Cheers,
Carl

**Comment by philhzss** [comment]
@foote-darrell 
The OpenVR runtime is not installed by us, you don't have to install anything extra, if you already have SteamVR running then all should work. If SteamVR works and you installed our latest commit and it still won't load properly, maybe we need to do some further testing (we've only tested this on 2 PCs so far)

As for the python3 command, I have not even tried it, we copied the build.MD from the original repo. I've always been compiling it by doing exactly the steps in the "How to build for windows" section. Since we had just quickly added "do the following instructs and after extract OpenVR to extern", I cleaned it up a bit and updated the document, but this is what I've been doing (I have had to re-build and re-compile dozens of times now and it has always worked for me):
![image](https://user-images.githubusercontent.com/41757256/136309581-b2b198d8-ee83-4a3e-86d5-8e60e1ad9079.png)

**Comment by fordcars** [comment]
@foote-darrell Did you install SteamVR from Steam? It might be necessary to do that if you haven't already.

**Comment by foote-darrell** [comment]
I installed SteamVR. It now says no HMD (presumably meaning _"Head Mounted Display"_) is missing. Is it nesecary to also have a headset mounted? Didn't you previously say that it wasn't required, or even wasn't possible yet?
![image](https://user-images.githubusercontent.com/70550621/136468502-a5ef84cb-e8f4-449c-844f-5d26ec4d1113.png)

**Comment by fordcars** [comment]
Hey @foote-darrell, looks like you're getting there! Currently, the game will not run unless you have a VR headset (HTC Vive, Valve Index, Oculus, etc) plugged in. Another solution is using your phone and an app like iVRy to simulate a VR headset. The game still runs on the computer screen, but will require a headset to be plugged in at startup.
