### ISSUE TITLE
Implement first person mode

### ISSUE THREAD

**Issue by philhzss** [fordcars/OttoMatic-VR#2]
# Implement first person view - basics
- [x] Make camera position = player head position (first person), & LookAtPoint = forward
- [x] ~~Remove all acceleration and "smoothing" from camera~~ Not deemed necessary, marking as done
- [x] Slow turning/rotation speed
  - [x] When walking
  - [x] When standing
- [x] #1
  - Not strictly required for VR, but since we'll be changing the turn controls to strafe, without mouse control of the camera the game will be unplayable / untestable
- [x] #4

<br>

## Figure out what to do with animations
- [x] Jump jet -> Camera currently floats at start point. Consider nausea for VR though #3
- [x] Otto bend over to pickup powerup -> We should never move player head in VR. Do nothing? Freeze cam?
  - No longer an issue with player relative controls

## Verify camera in special levels / unique events
- [x] Rocket landing (intro each level)?? Camera still in player head?
- [x] ~~Saucer level - to figure out~~ This level will probably never be first person view. We will figure out what to do with this level when we get there, for now ignoring, not a big deal.
- [x] Jungle level (big Otto) 
  - Has been tested, works fine without modification. @fordcars suggests shrinking world scale when big Otto

**Comment by philhzss** [comment]
Mouse control should rotate Otto on himself (without moving his coords), and keyboard buttons should strafe him

**Comment by foote-darrell** [comment]
Now how _can_ I change the desktop game to first person?
